# Generated by Django 3.1.5 on 2021-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='following',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='notification_period',
            field=models.IntegerField(default=2),
        ),
    ]
