# Generated by Django 3.1.5 on 2021-01-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_post_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolloweFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='main.profile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='main.profile')),
            ],
        ),
    ]
